import {addParams,compactDate,join,normalize} from "./utm";
export type Option={label:string,value:string}; export type Field={key:string,label:string,type:"text"|"url"|"select"|"date"|"month",required?:boolean,options?:Option[],dynamic?:"campaign_name"|"event_name"}; export type Channel={id:string,label:string,fields:Field[],build:(v:Record<string,string>)=>{generatedUrl:string,parameters:Record<string,string>}};
const opts=(a:string[])=>a.map(value=>({label:value.replaceAll("_"," "),value}));
const language=opts(["nl","fr","en"]),region=opts(["wallonia","flanders","brussels","all_regions"]),objective=opts(["awareness","consideration","decision"]),formats=opts(["opinion","news","casestudy","smartdeals","event","vacancy","academy","survey","marketing_info","agoria_products_and_services","tech_belgium_updates","business_group_updates"]),assets=opts(["post_link","post_video","job_posting","video","audio","banner","native","panel","postcard","rollup_banner","presentation","display"]);
const campaignFields:Field[]=[{key:"language",label:"Language",type:"select",required:true,options:language},{key:"region",label:"Region",type:"select",required:true,options:region},{key:"objective",label:"Objective",type:"select",required:true,options:objective},{key:"campaign",label:"Campaign name",type:"select",required:true,dynamic:"campaign_name"}];
const result=(v:Record<string,string>,source:string,medium:string,campaign:string,content?:string)=>{const parameters={utm_source:normalize(source),utm_medium:normalize(medium),utm_campaign:campaign,...(content?{utm_content:content}:{})};return{parameters,generatedUrl:addParams(v.destination_url,parameters)}};
export const channels:Channel[]=[
{id:"organic-social",label:"Organic Social",fields:[{key:"destination_url",label:"Destination URL",type:"url",required:true},{key:"source",label:"Social medium",type:"select",required:true,options:opts(["facebook","instagram","linkedin"])},...campaignFields,{key:"content_format",label:"Content format",type:"select",required:true,options:formats},{key:"date",label:"Publication date",type:"date",required:true},{key:"asset",label:"Asset type",type:"select",required:true,options:assets},{key:"subject",label:"Subject",type:"text",required:true}],build:v=>result(v,v.source,"social",join(v.language,v.region,v.objective,v.campaign,v.content_format,compactDate(v.date)),join(v.asset,v.subject))},
{id:"meta-ads",label:"Meta Ads",fields:[{key:"destination_url",label:"Destination URL",type:"url",required:true},...campaignFields],build:v=>{const parameters={utm_source:"{{site_source_name}}",utm_medium:"cpc",utm_campaign:"{{campaign.name}}",utm_content:"{{ad.name}}",utm_term:"{{adset.name}}"};return{parameters,generatedUrl:addParams(v.destination_url,parameters)}}},
{id:"linkedin-ads",label:"LinkedIn Ads",fields:[{key:"destination_url",label:"Destination URL",type:"url",required:true},...campaignFields,{key:"month",label:"Month",type:"month",required:true},{key:"creative",label:"Creative",type:"text",required:true}],build:v=>result(v,"linkedin","cpc",join(v.language,v.region,v.objective,v.campaign,compactDate(v.month)),join(v.creative))},
{id:"google-ads",label:"Google Ads",fields:[...campaignFields,{key:"month",label:"Month",type:"month",required:true},{key:"content",label:"Ad content",type:"text",required:true}],build:v=>{const parameters={utm_source:"google",utm_medium:"cpc",utm_campaign:join(v.language,v.region,v.objective,v.campaign,compactDate(v.month)),utm_content:join(v.content)};return{parameters,generatedUrl:"{lpurl}?"+new URLSearchParams(parameters).toString()}}},
{id:"media-buying",label:"Media Buying",fields:[{key:"destination_url",label:"Destination URL",type:"url",required:true},{key:"source",label:"Website / platform",type:"text",required:true},...campaignFields,{key:"month",label:"Month",type:"month",required:true},{key:"asset",label:"Asset type",type:"select",required:true,options:assets},{key:"creative",label:"Creative",type:"text",required:true}],build:v=>result(v,v.source,"cpc",join(v.language,v.region,v.objective,v.campaign,compactDate(v.month)),join(v.asset,v.creative))},
{id:"hubspot-email",label:"HubSpot Email",fields:[{key:"destination_url",label:"Destination URL",type:"url",required:true},{key:"source",label:"Email type",type:"select",required:true,options:opts(["hs_email","hs_automation"])},...campaignFields,{key:"event",label:"Event name (optional)",type:"select",dynamic:"event_name"},{key:"year",label:"Year",type:"text",required:true},{key:"content",label:"Email detail",type:"text",required:true}],build:v=>result(v,v.source,"email",join(v.language,v.region,v.objective,v.campaign,v.event,v.year),join(v.content))},
{id:"offline",label:"Offline",fields:[{key:"destination_url",label:"Destination URL",type:"url",required:true},{key:"medium",label:"Offline medium",type:"select",required:true,options:opts(["brochure","digital_screen","signalisation","goodie","postcard","rollup_banner","presentation"])},{key:"language",label:"Language",type:"select",required:true,options:language},{key:"region",label:"Region",type:"select",required:true,options:region},{key:"campaign",label:"Campaign name",type:"select",required:true,dynamic:"campaign_name"},{key:"event",label:"Event name (optional)",type:"select",dynamic:"event_name"},{key:"year",label:"Year",type:"text",required:true},{key:"content",label:"Variant",type:"text",required:true}],build:v=>result(v,"offline",v.medium,join(v.language,v.region,v.campaign,v.event,v.year),join(v.content))},
{id:"short-urls",label:"Short URLs",fields:[{key:"destination_url",label:"Final destination URL",type:"url",required:true},{key:"source",label:"Short URL alias",type:"text",required:true},{key:"campaign",label:"Campaign name",type:"select",required:true,dynamic:"campaign_name"}],build:v=>result(v,v.source,"short_url",join(v.campaign))}
];
